module.exports = [
  {
    key: "all",
    label: "全部",
    url: "/guides/",
    title: "全部指南",
    heading: "找到你的配置路径。",
    description: "浏览 cat 内部署、局域网共享和各平台客户端共存指南。",
  },
  {
    key: "cat",
    label: "cat",
    url: "/guides/cat/",
    title: "cat 部署指南",
    heading: "在 cat 内部署代理。",
    description: "这里只收录 PeppaPig (v2rayA) 和 Clash 两套 cat 内部署方案。",
  },
  {
    key: "cross-platform",
    label: "跨平台",
    url: "/guides/cross-platform/",
    title: "跨平台共存指南",
    heading: "配置跨平台客户端共存。",
    description: "让桌面端与移动端代理客户端和 cat 的 VPN 进程稳定共存。",
    platform: "跨平台",
  },
  {
    key: "ios",
    label: "iOS",
    url: "/guides/ios/",
    title: "iOS 共存指南",
    heading: "配置 iOS 客户端共存。",
    description: "调整 iOS 代理客户端的路由与网络模式，保留 cat 访问能力。",
    platform: "iOS",
  },
  {
    key: "macos",
    label: "macOS",
    url: "/guides/macos/",
    title: "macOS 共存指南",
    heading: "配置 macOS 客户端共存。",
    description: "处理 macOS 代理客户端与 cat VPN 进程之间的路由关系。",
    platform: "macOS",
  },
];
